spring.application.name=order-management-api

spring.datasource.url=jdbc:postgresql://localhost:5432/order_management_db
spring.datasource.username=admin
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update

jwt.secret=89012171748012890438910248910945
jwt.expiration.ms=3600000

spring.config.import=optional:file:.env[.properties]
security.token.secret=${JWT_SECRET}